# Generated by Django 4.0.6 on 2022-07-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Inquiry',
            new_name='Contact',
        ),
    ]
